// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.OperationsHistory.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CashOutState.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CashOutState
    {
        [EnumMember(Value = "Regular")]
        Regular,
        [EnumMember(Value = "Request")]
        Request,
        [EnumMember(Value = "Done")]
        Done,
        [EnumMember(Value = "Cancelled")]
        Cancelled
    }
    internal static class CashOutStateEnumExtension
    {
        internal static string ToSerializedValue(this CashOutState? value)
        {
            return value == null ? null : ((CashOutState)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CashOutState value)
        {
            switch( value )
            {
                case CashOutState.Regular:
                    return "Regular";
                case CashOutState.Request:
                    return "Request";
                case CashOutState.Done:
                    return "Done";
                case CashOutState.Cancelled:
                    return "Cancelled";
            }
            return null;
        }

        internal static CashOutState? ParseCashOutState(this string value)
        {
            switch( value )
            {
                case "Regular":
                    return CashOutState.Regular;
                case "Request":
                    return CashOutState.Request;
                case "Done":
                    return CashOutState.Done;
                case "Cancelled":
                    return CashOutState.Cancelled;
            }
            return null;
        }
    }
}
