// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.OperationsHistory.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.OperationsHistory;
    using Lykke.Service.OperationsHistory.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EditHistoryEntryModel
    {
        /// <summary>
        /// Initializes a new instance of the EditHistoryEntryModel class.
        /// </summary>
        public EditHistoryEntryModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EditHistoryEntryModel class.
        /// </summary>
        public EditHistoryEntryModel(string id = default(string), string blockChainHash = default(string), int? state = default(int?))
        {
            Id = id;
            BlockChainHash = blockChainHash;
            State = state;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BlockChainHash")]
        public string BlockChainHash { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "State")]
        public int? State { get; set; }

    }
}
