// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.OperationsHistory.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for HistoryOperationType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum HistoryOperationType
    {
        [EnumMember(Value = "CashIn")]
        CashIn,
        [EnumMember(Value = "CashOut")]
        CashOut,
        [EnumMember(Value = "Trade")]
        Trade,
        [EnumMember(Value = "LimitTrade")]
        LimitTrade
    }
    internal static class HistoryOperationTypeEnumExtension
    {
        internal static string ToSerializedValue(this HistoryOperationType? value)
        {
            return value == null ? null : ((HistoryOperationType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this HistoryOperationType value)
        {
            switch( value )
            {
                case HistoryOperationType.CashIn:
                    return "CashIn";
                case HistoryOperationType.CashOut:
                    return "CashOut";
                case HistoryOperationType.Trade:
                    return "Trade";
                case HistoryOperationType.LimitTrade:
                    return "LimitTrade";
            }
            return null;
        }

        internal static HistoryOperationType? ParseHistoryOperationType(this string value)
        {
            switch( value )
            {
                case "CashIn":
                    return HistoryOperationType.CashIn;
                case "CashOut":
                    return HistoryOperationType.CashOut;
                case "Trade":
                    return HistoryOperationType.Trade;
                case "LimitTrade":
                    return HistoryOperationType.LimitTrade;
            }
            return null;
        }
    }
}
