// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.OperationsHistory.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HistoryEntryWalletResponse
    {
        /// <summary>
        /// Initializes a new instance of the HistoryEntryWalletResponse class.
        /// </summary>
        public HistoryEntryWalletResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HistoryEntryWalletResponse class.
        /// </summary>
        public HistoryEntryWalletResponse(System.DateTime dateTime, double amount, string currency = default(string), string opType = default(string), string customData = default(string))
        {
            DateTime = dateTime;
            Amount = amount;
            Currency = currency;
            OpType = opType;
            CustomData = customData;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateTime")]
        public System.DateTime DateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OpType")]
        public string OpType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomData")]
        public string CustomData { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
