// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.OperationsHistory.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TradeHistoryOperation
    {
        /// <summary>
        /// Initializes a new instance of the TradeHistoryOperation class.
        /// </summary>
        public TradeHistoryOperation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TradeHistoryOperation class.
        /// </summary>
        public TradeHistoryOperation(double volume, bool isSettled, string id = default(string), string dateTime = default(string), string asset = default(string), string limitOrderId = default(string), string marketOrderId = default(string), string contextOperationType = default(string), string state = default(string))
        {
            Id = id;
            DateTime = dateTime;
            Asset = asset;
            Volume = volume;
            IsSettled = isSettled;
            LimitOrderId = limitOrderId;
            MarketOrderId = marketOrderId;
            ContextOperationType = contextOperationType;
            State = state;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateTime")]
        public string DateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsSettled")]
        public bool IsSettled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LimitOrderId")]
        public string LimitOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarketOrderId")]
        public string MarketOrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContextOperationType")]
        public string ContextOperationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "State")]
        public string State { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
