// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.OperationsHistory.AutorestClient
{
    using Lykke.Service;
    using Lykke.Service.OperationsHistory;
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for OperationsHistoryAPI.
    /// </summary>
    public static partial class OperationsHistoryAPIExtensions
    {
            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IsAliveResponse IsAlive(this IOperationsHistoryAPI operations)
            {
                return operations.IsAliveAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IsAliveResponse> IsAliveAsync(this IOperationsHistoryAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.IsAliveWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='page'>
            /// </param>
            public static object GetOperationsHistoryAllPaged(this IOperationsHistoryAPI operations, string clientId = default(string), int? page = default(int?))
            {
                return operations.GetOperationsHistoryAllPagedAsync(clientId, page).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='page'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetOperationsHistoryAllPagedAsync(this IOperationsHistoryAPI operations, string clientId = default(string), int? page = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetOperationsHistoryAllPagedWithHttpMessagesAsync(clientId, page, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            public static object GetOperationsHistoryAll(this IOperationsHistoryAPI operations, string clientId = default(string), int? top = default(int?), int? skip = default(int?))
            {
                return operations.GetOperationsHistoryAllAsync(clientId, top, skip).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetOperationsHistoryAllAsync(this IOperationsHistoryAPI operations, string clientId = default(string), int? top = default(int?), int? skip = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetOperationsHistoryAllWithHttpMessagesAsync(clientId, top, skip, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='operationType'>
            /// </param>
            /// <param name='assetId'>
            /// </param>
            /// <param name='page'>
            /// </param>
            public static object GetOperationsHistoryAllByOpTypeAndAssetPaged(this IOperationsHistoryAPI operations, string clientId = default(string), string operationType = default(string), string assetId = default(string), int? page = default(int?))
            {
                return operations.GetOperationsHistoryAllByOpTypeAndAssetPagedAsync(clientId, operationType, assetId, page).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='operationType'>
            /// </param>
            /// <param name='assetId'>
            /// </param>
            /// <param name='page'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetOperationsHistoryAllByOpTypeAndAssetPagedAsync(this IOperationsHistoryAPI operations, string clientId = default(string), string operationType = default(string), string assetId = default(string), int? page = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetOperationsHistoryAllByOpTypeAndAssetPagedWithHttpMessagesAsync(clientId, operationType, assetId, page, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='operationType'>
            /// </param>
            /// <param name='assetId'>
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            public static object GetOperationsHistoryAllByOpTypeAndAsset(this IOperationsHistoryAPI operations, string clientId = default(string), string operationType = default(string), string assetId = default(string), int? top = default(int?), int? skip = default(int?))
            {
                return operations.GetOperationsHistoryAllByOpTypeAndAssetAsync(clientId, operationType, assetId, top, skip).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='operationType'>
            /// </param>
            /// <param name='assetId'>
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetOperationsHistoryAllByOpTypeAndAssetAsync(this IOperationsHistoryAPI operations, string clientId = default(string), string operationType = default(string), string assetId = default(string), int? top = default(int?), int? skip = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetOperationsHistoryAllByOpTypeAndAssetWithHttpMessagesAsync(clientId, operationType, assetId, top, skip, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='operationType'>
            /// </param>
            /// <param name='page'>
            /// </param>
            public static object GetOperationsHistoryAllByOpTypePaged(this IOperationsHistoryAPI operations, string clientId = default(string), string operationType = default(string), int? page = default(int?))
            {
                return operations.GetOperationsHistoryAllByOpTypePagedAsync(clientId, operationType, page).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='operationType'>
            /// </param>
            /// <param name='page'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetOperationsHistoryAllByOpTypePagedAsync(this IOperationsHistoryAPI operations, string clientId = default(string), string operationType = default(string), int? page = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetOperationsHistoryAllByOpTypePagedWithHttpMessagesAsync(clientId, operationType, page, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='operationType'>
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            public static object GetOperationsHistoryAllByOpType(this IOperationsHistoryAPI operations, string clientId = default(string), string operationType = default(string), int? top = default(int?), int? skip = default(int?))
            {
                return operations.GetOperationsHistoryAllByOpTypeAsync(clientId, operationType, top, skip).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='operationType'>
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetOperationsHistoryAllByOpTypeAsync(this IOperationsHistoryAPI operations, string clientId = default(string), string operationType = default(string), int? top = default(int?), int? skip = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetOperationsHistoryAllByOpTypeWithHttpMessagesAsync(clientId, operationType, top, skip, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='assetId'>
            /// </param>
            /// <param name='page'>
            /// </param>
            public static object GetOperationsHistoryAllByAssetPaged(this IOperationsHistoryAPI operations, string clientId = default(string), string assetId = default(string), int? page = default(int?))
            {
                return operations.GetOperationsHistoryAllByAssetPagedAsync(clientId, assetId, page).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='assetId'>
            /// </param>
            /// <param name='page'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetOperationsHistoryAllByAssetPagedAsync(this IOperationsHistoryAPI operations, string clientId = default(string), string assetId = default(string), int? page = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetOperationsHistoryAllByAssetPagedWithHttpMessagesAsync(clientId, assetId, page, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='assetId'>
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            public static object GetOperationsHistoryAllByAsset(this IOperationsHistoryAPI operations, string clientId = default(string), string assetId = default(string), int? top = default(int?), int? skip = default(int?))
            {
                return operations.GetOperationsHistoryAllByAssetAsync(clientId, assetId, top, skip).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// </param>
            /// <param name='assetId'>
            /// </param>
            /// <param name='top'>
            /// </param>
            /// <param name='skip'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetOperationsHistoryAllByAssetAsync(this IOperationsHistoryAPI operations, string clientId = default(string), string assetId = default(string), int? top = default(int?), int? skip = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetOperationsHistoryAllByAssetWithHttpMessagesAsync(clientId, assetId, top, skip, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
